CREATE DATABASE EduX;

USE EduX;
-- CRIAR TABLE PERFIL

CREATE TABLE Perfil(
	IdPerfil UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Permissao VARCHAR(50)
);

-- CRIAR TABLE CATEGORIA
CREATE TABLE Categoria(
	IdCategoria UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Tipo		VARCHAR(100)
);
-- CRIAR TABLE USUARIO
CREATE TABLE Usuario(
	IdUsuario          UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,

	Nome				VARCHAR(255) NOT NULL,
	Senha				VARCHAR(255) NOT NULL,
	Email				VARCHAR(100) NOT NULL,
	DataCadastro		DATETIME,
	DataUltimoAcesso	DATETIME,
	

	IdPerfil			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Perfil(IdPerfil) NOT NULL
);
-- CRIAR TABLE DICA
CREATE TABLE Dica(
	IdDica		UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,

	Texto		VARCHAR(255),
	Imagem		VARCHAR(255),

	IdUsuario		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario)

);
-- CRIAR TABLE Instituicao
CREATE  TABLE Instituicao (
	IdInstituicao	UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,

	Nome			VARCHAR(255) NOT NULL,
	Logradouro		VARCHAR(255) NOT NULL,
	Numero			VARCHAR(255) NOT NULL,
	Complemento		VARCHAR(255),
	Bairro			VARCHAR(255) NOT NULL,
	Cidade			VARCHAR(255) NOT NULL,
	UF				CHAR(2)		 NOT NULL,
	CEP				VARCHAR(15)  NOT NULL

);


-- CRIAR TABLE OBJETIVO
CREATE TABLE Objetivo(
	IdObjetivo		UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Descricao		VARCHAR(255),

	IdCategoria	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Categoria(IdCategoria) NOT NULL


);
-- CRIAR TABLE CURSO
CREATE TABLE Curso(
	IdCurso		UNIQUEIDENTIFIER PRIMARY KEY  NOT NULL,
	Titulo		VARCHAR(255),

	IdInstituicao	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao(IdInstituicao)NOT NULL
);

-- CRIAR TABLE TURMA
CREATE TABLE Turma(
	IdTurma			UNIQUEIDENTIFIER PRIMARY KEY  NOT NULL,
	Descricao		VARCHAR(255),

	IdCurso			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Curso(IdCurso) NOT NULL
);
-- CRIAR TABLE Curtida
CREATE TABLE Curtida(
	IdCurtida		UNIQUEIDENTIFIER PRIMARY KEY  NOT NULL,

	IdUsuario		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario	(IdUsuario) NOT NULL,
	IdDica			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Dica		(IdDica) NOT NULL
);

-- CRIAR TABLE ProfessorTurma
CREATE TABLE ProfessorTurma(
	IdProfessorTurma	UNIQUEIDENTIFIER PRIMARY KEY  NOT NULL,
	Descricao			VARCHAR(255),

	IdUsuario			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario	(IdUsuario) NOT NULL,
	IdTurma				UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Turma	(IdTurma)	NOT NULL
);


-- CRIAR TABLE Aluno_Turma
CREATE TABLE AlunoTurma(
	IdAlunoTurma	UNIQUEIDENTIFIER PRIMARY KEY  NOT NULL,
	Matricula		VARCHAR(50) NOT NULL,

	IdTurma			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Turma	(IdTurma) NOT NULL,
	IdUsuario		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario	(IdUsuario) NOT NULL
);

-- CRIAR TABLE Aluno_Objetivo
CREATE TABLE ObjetivoAluno(

	IdObjetivoAluno		UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	DataAlcancado		DATETIME,
	Nota				DECIMAL DEFAULT NULL,

	IdAlunoTurma		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES AlunoTurma(IdAlunoTurma),
	IdObjetivo			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Objetivo(IdObjetivo)

);
